title: Know Thy Starspot
description: > # this means to ignore newlines until "baseurl:"
  A Cool Stars 20 Splinter Session
baseurl: "" # the subpath of your site, e.g. /blog
url: "knowthystarspot.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "../css/2016_style/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2018_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/explore/tags/knowthystarspot/
  - title: twitter
    url: https://twitter.com/hashtag/KnowThyStarspot

# Build settings
markdown: kramdown
permalink: pretty
